/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "pr8"
include("services")
include("services:service-discovery")
findProject(":services:service-discovery")?.name = "service-discovery"
include("services:config-server")
findProject(":services:config-server")?.name = "config-server"
include("services:load-balancer")
findProject(":services:api-gateway")?.name = "api-gateway"
include("services:user-service")
findProject(":services:load-balancer")?.name = "load-balancer"
include("services:api-gateway")
findProject(":services:user-service")?.name = "user-service"
include("services:pizza-service")
findProject(":services:pizza-service")?.name = "pizza-service"
include("services:delivery-service")
findProject(":services:delivery-service")?.name = "delivery-service"
