apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: pizza-service
  name: pizza-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pizza-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: pizza-service
    spec:
      containers:
        - image: p0pl3/pizza-service:latest
          name: pizza-service
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
