apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-db1
  name: postgres-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres-db1
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: db1
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16-alpine3.19
          name: postgres-db1
          ports:
            - containerPort: 5432
              protocol: TCP
#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: db1-data
#      restartPolicy: Always
#      volumes:
#        - name: db1-data
#          persistentVolumeClaim:
#            claimName: db1-data
